# Generated by Django 2.0.4 on 2019-05-22 02:16

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('apartamento', models.CharField(max_length=6, verbose_name='Apartamento')),
            ],
            options={
                'verbose_name': 'Apartamentos',
                'verbose_name_plural': 'Apartamentos',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='AreaComum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('nomeArea', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Area Comum',
                'verbose_name_plural': 'Áreas Comuns',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('bloco', models.CharField(max_length=15, verbose_name='Bloco')),
            ],
            options={
                'verbose_name': 'Bloco',
                'verbose_name_plural': 'Blocos',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaDeProblema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('nomeCategoria', models.CharField(max_length=100, unique=True, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCadastro', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('dataInteracao', models.DateTimeField(auto_now=True, verbose_name='Data de interação')),
                ('protocolo', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Protocolo')),
                ('statusChamado', models.CharField(choices=[('Em analise', 'Em analise'), ('Em andamento', 'Em andamento'), ('Finalizado', 'Finalizado')], default='Em analise', max_length=20, verbose_name='Status do chamado')),
                ('envolveAreaComum', models.BooleanField(verbose_name='Problema em área comum')),
                ('prioridade', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Prioridade')),
                ('descricao', models.TextField(verbose_name='Descreva o problema')),
                ('img', models.ImageField(blank=True, upload_to='sistema/chamados', verbose_name='Envie uma foto')),
                ('apartamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sistema.Apartamento')),
                ('areaComum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sistema.AreaComum', verbose_name='Selecione uma Área comum')),
                ('categoriaProblema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.CategoriaDeProblema', verbose_name='Categoria do problema')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Empreendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('nomeEmpreendimento', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Empreendimento',
                'verbose_name_plural': 'Empreendimentos',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='EventosChamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCadastro', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('descicaoEvento', models.CharField(max_length=30, unique=True, verbose_name='Protocolo')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.Chamado')),
            ],
            options={
                'verbose_name': 'Evento de Chamado',
                'verbose_name_plural': 'Eventos de Chamados',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('telefone1', models.CharField(blank=True, max_length=15, null=True)),
                ('telefone2', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='chamado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.Usuarios'),
        ),
        migrations.AddField(
            model_name='bloco',
            name='empreendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.Empreendimento', verbose_name='Empreendimento'),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='bloco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.Bloco', verbose_name='Bloco'),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sistema.Usuarios'),
        ),
    ]
