# Generated by Django 2.0.4 on 2019-05-22 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloco',
            name='empreendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empreendimentos', to='sistema.Empreendimento', verbose_name='Empreendimento'),
        ),
    ]
