# Generated by Django 2.0.4 on 2018-05-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='Cpf'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='telefoneCelular',
            field=models.CharField(max_length=11, verbose_name='Telefone celular'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='telefoneFixo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefone fixo'),
        ),
    ]
