# Generated by Django 2.0.4 on 2019-05-30 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20190529_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoschamado',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Chamado'),
        ),
    ]
