# Generated by Django 2.0.4 on 2019-05-22 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20190522_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloco',
            name='empreendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.Empreendimento', verbose_name='Empreendimento'),
        ),
    ]
