# Generated by Django 2.0.4 on 2019-05-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='apartamentos',
            field=models.ManyToManyField(to='sistema.Apartamento'),
        ),
    ]
