# Generated by Django 2.0.4 on 2019-06-11 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20190529_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='feedbackUsuario',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Feedback dado pelo Usuário'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='novosEventos',
            field=models.BooleanField(default=False, verbose_name='Novos eventos disponíveis'),
        ),
    ]
