# Generated by Django 2.0.4 on 2019-05-19 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema', '0003_usuarios_apartamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='usuario',
            field=models.ForeignKey(default=0.0004952947003467063, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
