# Generated by Django 2.0.4 on 2019-05-19 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_chamado_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventosChamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCadastro', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('descicaoEvento', models.CharField(max_length=30, unique=True, verbose_name='Protocolo')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.Chamado')),
            ],
            options={
                'verbose_name': 'Evento de Chamado',
                'verbose_name_plural': 'Eventos de Chamados',
                'ordering': ['-pk'],
            },
        ),
    ]
