# Generated by Django 2.0.4 on 2019-05-25 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20190525_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='bloco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocos', to='sistema.Bloco', verbose_name='Bloco'),
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proprietarios', to='sistema.Usuarios'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='empreendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empreendimentos', to='sistema.Empreendimento', verbose_name='Empreendimento'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='apartamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apartamentos', to='sistema.Apartamento'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='areaComum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='areasComuns', to='sistema.AreaComum', verbose_name='Selecione uma Área comum'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='sistema.Usuarios'),
        ),
    ]
