# Generated by Django 2.0.4 on 2019-05-19 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_eventoschamado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areacomum',
            name='empreendimento',
        ),
        migrations.AddField(
            model_name='chamado',
            name='areaComum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sistema.AreaComum', verbose_name='Selecione uma Área comum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chamado',
            name='envolveAreaComum',
            field=models.BooleanField(default=1, verbose_name='Problema em áre comum'),
            preserve_default=False,
        ),
    ]
