# Generated by Django 2.0.4 on 2019-06-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_auto_20190611_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='inicioGarantia',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio da Garantia'),
        ),
    ]
