# Generated by Django 2.0.4 on 2019-05-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_auto_20190519_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='envolveAreaComum',
            field=models.BooleanField(verbose_name='Problema em área comum'),
        ),
    ]
