# Generated by Django 2.0.4 on 2019-05-26 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_auto_20190525_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='bloco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.Bloco', verbose_name='Bloco'),
        ),
    ]
