# Generated by Django 2.0.4 on 2019-06-12 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_auto_20190611_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='apartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.Apartamento'),
        ),
    ]
