# Generated by Django 2.0.4 on 2019-05-19 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_auto_20190519_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='areaComum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sistema.AreaComum', verbose_name='Selecione uma Área comum'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='img',
            field=models.ImageField(blank=True, upload_to='sistema/chamados', verbose_name='Enexe uma foto'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='protocolo',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Protocolo'),
        ),
    ]
