# Generated by Django 2.0.4 on 2019-05-19 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_auto_20190519_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='apartamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sistema.Apartamento'),
        ),
    ]
