# Generated by Django 2.0.4 on 2019-06-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
