# Generated by Django 2.0.4 on 2019-05-20 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema', '0009_chamado_apartamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='apartamentos',
        ),
        migrations.AddField(
            model_name='apartamento',
            name='dono',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
