# Generated by Django 2.0.4 on 2019-05-20 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_auto_20190519_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='dono',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
