# Generated by Django 2.0.4 on 2019-06-13 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0012_auto_20190613_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='limiteChamadosDia',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Número limite de chamados por dia'),
        ),
    ]
