# Generated by Django 2.0.4 on 2019-05-20 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0012_auto_20190519_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='prioridade',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Prioridade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chamado',
            name='img',
            field=models.ImageField(blank=True, upload_to='sistema/chamados', verbose_name='Envie uma foto'),
        ),
    ]
