# Generated by Django 2.0.4 on 2019-06-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0013_usuarios_limitechamadosdia'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='emailMensagensAutomaticas',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email para envio de mensagens automáticas'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='hostEmailMensagensAutomaticas',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=100, null=True, verbose_name='Host'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='portaEmailMensagensAutomaticas',
            field=models.CharField(blank=True, default='587', max_length=10, null=True, verbose_name='Porta'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='senhaEmailMensagensAutomaticas',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Senha'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tlsEmailMensagensAutomaticas',
            field=models.BooleanField(default=True, verbose_name='Usar TLS'),
        ),
    ]
