# Generated by Django 2.0.4 on 2019-06-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0014_auto_20190613_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='emailMensagensAutomaticas',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='hostEmailMensagensAutomaticas',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='portaEmailMensagensAutomaticas',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='senhaEmailMensagensAutomaticas',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='tlsEmailMensagensAutomaticas',
        ),
    ]
