# Generated by Django 2.0.4 on 2019-06-15 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0015_auto_20190614_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='prioridade',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Prioridade'),
        ),
    ]
