# Generated by Django 2.0.4 on 2019-06-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0016_auto_20190615_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='sistema/chamados', verbose_name='Envie uma foto'),
        ),
    ]
