# Generated by Django 2.0.4 on 2019-05-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0016_auto_20190520_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloco',
            name='bloco',
            field=models.CharField(blank=True, max_length=15, verbose_name='Bloco'),
        ),
    ]
