# Generated by Django 2.0.4 on 2019-05-21 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0017_auto_20190521_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloco',
            name='bloco',
            field=models.CharField(max_length=15, verbose_name='Bloco'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='empreendimento',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='sistema.Empreendimento', verbose_name='Empreendimento'),
        ),
    ]
