# Generated by Django 2.0.4 on 2019-06-22 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0019_auto_20190621_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemupload',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sistema.Usuarios'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagemupload',
            name='img',
            field=models.ImageField(default=1, upload_to='sistema/chamados', verbose_name='Envie uma foto'),
            preserve_default=False,
        ),
    ]
