# Generated by Django 2.0.4 on 2019-05-21 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0019_auto_20190521_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='dono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sistema.Usuarios'),
        ),
    ]
