# Generated by Django 2.0.4 on 2019-05-21 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0020_auto_20190521_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.Usuarios'),
        ),
    ]
