# Generated by Django 2.0.4 on 2019-06-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0020_auto_20190621_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='novosEventos',
            field=models.BooleanField(verbose_name='Novos eventos disponíveis'),
        ),
    ]
